#include "stdafx.h"
#include "WeaponID.h"

std::map<int, std::string> WeaponIDToName = {
	{ WeaponID::Weapon_Ak47, "AK-47" },
	{ WeaponID::Weapon_Aug, "AUG" },
	{ WeaponID::Weapon_Awp, "AWP" },
	{ WeaponID::Weapon_C4, "Bomb" },
	{ WeaponID::Weapon_Decoy, "Decoy Grenade" },
	{ WeaponID::Weapon_Bizon, "PP-Bizon" },
	{ WeaponID::Weapon_Deagle, "Deagle" },
	{ WeaponID::Weapon_Elite, "Dual Elites" },
	{ WeaponID::Weapon_Famas, "Famas" },
	{ WeaponID::Weapon_Fiveseven, "Five-Seven" },
	{ WeaponID::Weapon_Flashbang, "Flashbang" },
	{ WeaponID::Weapon_G3sg1, "G3SG1" },
	{ WeaponID::Weapon_Galil, "Galil" },
	{ WeaponID::Weapon_Galilar, "Galil" },
	{ WeaponID::Weapon_Glock, "Glock" },
	{ WeaponID::Weapon_Hegrenade, "HE Grenade" },
	{ WeaponID::Weapon_Hkp2000, "P2000" },
	{ WeaponID::Weapon_Incgrenade, "Incendiary Grenade" },
	{ WeaponID::Weapon_KnifeCT, "Knife" },
	{ WeaponID::Weapon_Knifegg, "Knife" },
	{ WeaponID::Weapon_KnifeT, "Knife" },
	{ WeaponID::Weapon_M249, "M249" },
	{ WeaponID::Weapon_M3, "M3" },
	{ WeaponID::Weapon_M4a4, "M4A4" },
	{ WeaponID::Weapon_Mac10, "Mac-10" },
	{ WeaponID::Weapon_Mag7, "Mag-7" },
	{ WeaponID::Weapon_Molotov, "Molotov" },
	{ WeaponID::Weapon_Mp7, "MP7" },
	{ WeaponID::Weapon_Mp9, "MP9" },
	{ WeaponID::Weapon_Negev, "Negev" },
	{ WeaponID::Weapon_None, "No Weapon" },
	{ WeaponID::Weapon_Nova, "Nova" },
	{ WeaponID::Weapon_P250, "P250" },
	{ WeaponID::Weapon_P90, "P90" },
	{ WeaponID::Weapon_Sawedoff, "Sawed-off" },
	{ WeaponID::Weapon_Scar20, "SCAR-20" },
	{ WeaponID::Weapon_Scout, "SSG08 Scout" },
	{ WeaponID::Weapon_Sg550, "SG553" },
	{ WeaponID::Weapon_Sg552, "SG553" },
	{ WeaponID::Weapon_Sg556, "SG553" },
	{ WeaponID::Weapon_Smokegrenade, "Smoke Grenade" },
	{ WeaponID::Weapon_Taser, "Zeus Taser" },
	{ WeaponID::Weapon_Ssg08, "SSG08" },
	{ WeaponID::Weapon_Tec9, "Tec-9" },
	{ WeaponID::Weapon_Ump45, "UMP-45" },
	{ WeaponID::Weapon_Usp, "USP-S" },
	{ WeaponID::Weapon_Xm1014, "XM1014" },
	{ WeaponID::Weapon_M4a1S, "M4A1-S" }
};